import { Product } from "@/types/type";

export function GetProductItems(): Product[] {
  return [
    {
      id: 1,
      images: ["https://i.pinimg.com/736x/36/e9/6a/36e96a759226592840340d7df9eebfda.jpg"],
      name: "TEVISE T845 Casual Style Men Wrist Watch Date Display Full Steel Band Quartz Watch",
      description: "A sleek stainless-steel watch with precise quartz movement and a modern, versatile design.",
      price: 80020,
      progress: 85,
      itemsLeft: 85,
      ratings: 4,
      reviews: 6400,
      category: "accessories",
      subcategory: "watches",
      vendor: "Luxury Living Co.",
      variants: [
        { color: "black", sizes: ["Standard"] },
        { color: "silver", sizes: ["Standard"] },
      ],
    },
    {
      id: 2,
      images: ["https://i.pinimg.com/736x/ab/7c/4e/ab7c4e76bddedd77600204cf58810604.jpg"],
      name: "Men's Jacquard Pullover Hoodie - Navy / L",
      description: "A sleek stainless-steel watch with precise quartz movement and a modern, versatile design.",
      price: 70977,
      progress: 32,
      itemsLeft: 32,
      ratings: 3,
      reviews: 32000,
      category: "mens-fashion",
      subcategory: "mens-shirts",
      vendor: "Luxury Living Co.",
      variants: [
        { color: "navy", sizes: ["S", "M", "L", "XL"] },
        { color: "black", sizes: ["M", "L", "XL"] },
        { color: "red", sizes: ["S", "M", "L"] },
      ],
    },
    {
      id: 3,
      images: ["https://i.pinimg.com/564x/8c/90/e2/8c90e2c348da08b9c9cb38d2b5049e8d.jpg"],
      name: "Candy Color Pointed Toe Low Cut Stiletto High Heels Prom Shoes",
      description: "A sleek stainless-steel watch with precise quartz movement and a modern, versatile design.",
      price: 56536,
      progress: 56,
      itemsLeft: 56,
      ratings: 3,
      reviews: 43000,
      category: "womens-fashion",
      subcategory: "womens-shoes",
      vendor: "Luxury Living Co.",
      variants: [
        { color: "red", sizes: ["36", "37", "38", "39", "40"] },
        { color: "pink", sizes: ["37", "38", "39"] },
      ],
    },
    {
      id: 4,
      images: ["https://i.pinimg.com/736x/a4/ee/14/a4ee14303302dc2e75637b04e42a9b03.jpg"],
      name: "Modern Chic Round Nesting Coffee Table with Storage White Stone Coffee Table Set of 2",
      description: "A sleek stainless-steel watch with precise quartz movement and a modern, versatile design.",
      price: 95434,
      progress: 18,
      itemsLeft: 18,
      ratings: 4,
      reviews: 128400,
      category: "home-living",
      subcategory: "furniture",
      vendor: "Luxury Living Co.",
      variants: [
        { color: "white", sizes: ["Standard"] },
        { color: "beige", sizes: ["Standard"] },
      ],
    },
    {
      id: 5,
      images: ["https://i.pinimg.com/564x/7a/45/25/7a4525fed23ce54148599b480b2e18ae.jpg"],
      name: "Mercer41 Annemargaret 90.5\" Round Arm Sofa Polyester Blend in Blue",
      description: "A sleek stainless-steel watch with precise quartz movement and a modern, versatile design.",
      price: 99233,
      progress: 25,
      itemsLeft: 25,
      ratings: 4,
      reviews: 12000,
      category: "home-living",
      subcategory: "furniture",
      vendor: "Luxury Living Co.",
      variants: [
        { color: "teal", sizes: ["2-Seater", "3-Seater"] },
      ],
    },
    {
      id: 6,
      images: ["https://ak1.ostkcdn.com/img/mxc/02222021-gnp-lighting-PopCat_7.jpg?imwidth=400"],
      name: "Turin Modern Coffee Table",
      description: "A sleek stainless-steel watch with precise quartz movement and a modern, versatile design.",
      price: 63284,
      progress: 52,
      itemsLeft: 52,
      ratings: 4,
      reviews: 32400,
      category: "home-living",
      subcategory: "furniture",
      vendor: "Luxury Living Co.",
      variants: [
        { color: "white", sizes: ["Standard"] },
      ],
    },
    {
      id: 7,
      images: ["https://i.pinimg.com/736x/86/cf/ae/86cfaec5ae9d1b7bcdc2da53f803014e.jpg"],
      name: "Dodiy Modern L-Shaped White Corner Sectional Sofa 5-Seater",
      description: "A sleek stainless-steel watch with precise quartz movement and a modern, versatile design.",
      price: 97376,
      progress: 31,
      itemsLeft: 31,
      ratings: 3,
      reviews: 45900,
      category: "home-living",
      subcategory: "furniture",
      vendor: "Luxury Living Co.",
      variants: [
        { color: "white", sizes: ["5-Seater", "6-Seater"] },
      ],
    },
    {
      id: 8,
      images: ["https://i.pinimg.com/736x/98/3b/ae/983bae0b2b4d16b215bf1570306d86e3.jpg"],
      name: "Snuggle Circular Hollow Ceramic Vase - Nordic Flower Pot",
      description: "A sleek stainless-steel watch with precise quartz movement and a modern, versatile design.",
      price: 83943,
      progress: 51,
      itemsLeft: 51,
      ratings: 4,
      reviews: 9800,
      category: "home-living",
      subcategory: "home-storage",
      vendor: "Luxury Living Co.",
      variants: [
        { color: "gray", sizes: ["Small", "Medium", "Large"] },
      ],
    },
  ];
}
